### ISSUE TITLE
ng: command not found

### ISSUE THREAD

**Issue by jason-magnetic-io** [magneticio/buildserver#12]
The new repo `vamp-lifter-ui` introduces a new dependency for `buildserver`

```
project: vamp-lifter
version: 0.9.5-32-g78ad825
stashing /usr/local/src as /usr/local/stash/vamp-lifter-0.9.5-32-g78ad825
project: vamp-lifter-ui - https://github.com/magneticio/vamp-lifter-ui.git - master
Cloning into 'vamp-lifter-ui'...
ng build -prod
bash: ng: command not found
Makefile:27: recipe for target 'pack' failed
make: *** [pack] Error 127
```

**Comment by luciangabor** [comment]
I believe it wouldn't work. ng comes with the angular-cli node package, but pre-installing it globally doesn't really work. In the Makefile of the vamp-lifter-ui, before the ng build command it's necessary to run npm install
