### ISSUE TITLE
At least Ivy local dir is not mounted properly

### ISSUE THREAD

**Issue by dragoslav** [magneticio/buildserver#4]
At the end of Vamp build, files are stored to local ivy2 directories, for instance inside the container `/srv/cache/sbt/ivy2/local/io.vamp/vamp-gateway_driver_2.12/katana/jars/vamp-gateway_driver_2.12.jar` but these files are not on the host machine (~/.ivy2/local/io.vamp/...) 

This seems related to https://github.com/magneticio/buildserver/issues/2
Because not just that sbt needs to be downloaded but also all dependencies and they should be already available on host machine in ivy2 cache dir.

**Comment by iamtew** [comment]
I can't reproduce this, the `~/.ivy2/local` directory shows up correctly on my system, using the `default` target from the vamp Makefile: https://github.com/magneticio/vamp/blob/master/Makefile#L28-L41

Is your local ivy2 directory somewhere else than `$(HOME)/.ivy2` ?

**Comment by iamtew** [comment]
@dragoslav please add the following to `Makefile.local` in your local vamp repo, and run `make` and let me know the output.

```Makefile
.DEFAULT_GOAL := fixperms

BUILD_SERVER := magneticio/buildserver:katana

.PHONY: fixperms
fixperms:
	docker pull $(BUILD_SERVER)
	docker run \
		--interactive \
		--tty \
		--volume $(CURDIR):/srv/src \
		--volume $(DIR_SBT):/home/vamp/.sbt \
		--volume $(DIR_IVY):/home/vamp/.ivy2 \
		--workdir=/srv/src \
		--env BUILD_UID=$(shell id -u) \
		--env BUILD_GID=$(shell id -g) \
		$(BUILD_SERVER) \
			exit 0
```

**Comment by dragoslav** [comment]
```
docker pull magneticio/buildserver:katana
katana: Pulling from magneticio/buildserver
Digest: sha256:635975b49b9808f5f863344d5cc4bb1d57a4a6419f388320a658f0bdf1b6a7b0
Status: Image is up to date for magneticio/buildserver:katana
docker run \
		--interactive \
		--tty \
		--volume /Users/dragoslav/workspace/vamp:/srv/src \
		--volume /Users/dragoslav/.sbt:/home/vamp/.sbt \
		--volume /Users/dragoslav/.ivy2:/home/vamp/.ivy2 \
		--workdir=/srv/src \
		--env BUILD_UID=501 \
		--env BUILD_GID=20 \
		magneticio/buildserver:katana \
			exit 0

┌───────────────────╴Vamp Buildserver╶───────────────────┄
│
│ Source code: https://github.com/magneticio/buildserver
│ Version    : 0.4.3-1-g252fedf (katana)
│ Commit     : 252fedf6ff28519e17c53c4fb7bfd4e307fd2d2f
│ Build date : 2017-02-15T14:50:42Z
│
└────────────────────────────────────────────────────────┄

+ USERNAME=vamp
+ USERHOME=/home/vamp
+ ls -ltA /home/vamp
total 0
drwxr-xr-x 1 1000 50 272 Dec 28 21:16 .ivy2
drwxr-xr-x 1 1000 50 136 Dec 28 13:20 .sbt
+ [[ -z 501 ]]
+ [[ -z 20 ]]
+ echo 'Adding user inside docker container:' 'uid=501(vamp) gid=20(vamp)'
Adding user inside docker container: uid=501(vamp) gid=20(vamp)
+ groupadd --gid 20 vamp
+ useradd --uid 501 --gid 20 --home-dir /home/vamp vamp
useradd: warning: the home directory already exists.
Not copying any file from skel directory into it.
+ chown -R 501:20 /home/vamp
+ chmod -R 0755 /home/vamp
+ ls -ltA /home/vamp
total 0
drwxr-xr-x 1 1000 50 272 Dec 28 21:16 .ivy2
drwxr-xr-x 1 1000 50 136 Dec 28 13:20 .sbt
+ exec su vamp '--command=exit 0'
```

**Comment by iamtew** [comment]
This is an issue with Docker Toolbox, using Docker for Mac this works as expected.

The reason for keeping Docker Toolbox is to have something we can run Vamp quick-start on. But with the new reverse-proxy functionality in Vamp we can move away from using Docker Toolbox. Details regarding the quick-start in here: https://github.com/magneticio/vamp/issues/623
