### ISSUE TITLE
automated Vamp build and test pipeline

### ISSUE THREAD

**Issue by olafmol** [magneticio/buildserver#7]
- [ ] build script that works on both Mac OS X and *nix and pulls and builds katana docker images
- [ ] provision a build-server on AWS that can run build script
- [ ] scheduled task that runs build script, packages into docker images and pushes to docker hub (for katana images)
- [ ] create a script to provision a DC/OS cluster on AWS
- [ ] create a script that automatically deploys ES+Vamp katana (latest build) on DC/OS on AWS 
- [ ]  scheduled task that deploys katana ES+Vamp on DC/OS using the deployment script
- [ ] create a script that automatically runs Vamp Runner recipes against the Vamp installation and send mail with results
- [ ] scheduled task to run recipe testing script

**Comment by iamtew** [comment]
This issue was moved to magneticio/buildserver-loop#1
